# Generated by Django 6.1.1 on 2026-10-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatars',
            new_name='avatar',
        ),
    ]
