# Generated by Django 6.1 on 2026-09-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrollment_date',
            field=models.DateField(help_text='Дата зачисления.', verbose_name='Дата зачисления'),
        ),
    ]
