# Generated by Django 6.1 on 2026-10-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['last_name'], 'permissions': [('can_promote_student', 'can promote student'), ('can_expel_student', 'can expel student')], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
